accounts/urls.py
from django.urls import re_path
from django.contrib.auth import views as auth_views

from accounts import views

urlpatterns = [
    re_path(r"^send_login_email$", views.send_login_email, name="send_login_email"),
    re_path(r"^login$", views.login, name="login"),
    re_path(r"^logout$", auth_views.LogoutView.as_view(next_page="/"), name="logout"),
]

lists/urls.py
from django.urls import path, re_path
from lists import views

urlpatterns = [
    re_path(r"^new$", views.new_list, name="new_list"),
    re_path(r"^(\d+)/$", views.view_list, name="view_list"),
    re_path(r"^users/(.+)/$", views.my_lists, name="my_lists"),
    path("<int:list_id>/share/", views.share_list, name="share_list")
]

superlists/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from lists import views
from lists import urls as list_urls
from accounts import urls as accounts_urls
from lists import api_urls
from lists.api import router

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", views.home_page, name="home"),
    re_path("^lists/", include(list_urls)),
    re_path("^accounts/", include(accounts_urls)),
    re_path("^api/", include(api_urls)),
    re_path("^api-drf/", include(router.urls)),
]

accounts/models.py
import uuid

from django.contrib import auth
from django.db import models
from django.contrib.auth.models import (
    AbstractBaseUser,
    BaseUserManager,
)

# auth.signals.user_logged_in.disconnect(auth.models.update_last_login)


class ListUserManager(BaseUserManager):
    """Менеджер пользователя списка."""

    def create_user(self, email):
        """Создать пользователя."""
        ListUser.objects.create(email=email)

    def create_superuser(self, email, password):
        """Создать суперпользователя."""
        self.create_user(email)


class Token(models.Model):
    """Маркер."""
    email = models.EmailField()
    uid = models.CharField(default=uuid.uuid4, max_length=40)


# class ListUser(AbstractBaseUser, PermissionsMixin):
#     """Пользователь списка."""
#     email = models.EmailField(primary_key=True)
#     USERNAME_FIELD = 'email'
# # REQUIRED_FIELDS = ['email', 'height']
# objects = ListUserManager()
#
# @property
# def is_staff(self):
#     return self.email == 'sana451@mail.ru'
#
# @property
# def is_active(self):
#     return True


class ListUser(models.Model):
    """Пользователь списка."""
    email = models.EmailField(primary_key=True)
    REQUIRED_FIELDS = []
    USERNAME_FIELD = 'email'
    is_anonymous = False
    is_authenticated = True

lists/models.py
from django.conf import settings
from django.contrib.auth import get_user_model
from django.core.exceptions import ValidationError
from django.db import models
from django.urls import reverse


User = get_user_model()


class List(models.Model):
    """Список дел"""

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, blank=True, null=True, on_delete=models.CASCADE)
    shared_with = models.ManyToManyField(User, related_name="my_list")

    @property
    def name(self):
        """Имя."""
        return self.item_set.first().text

    def get_absolute_url(self):
        """Получить абсолютный url"""
        return reverse("view_list", args=[self.id])


class Item(models.Model):
    """Элемент списка"""
    text = models.TextField()
    list = models.ForeignKey(List, default=None, on_delete=models.CASCADE)

    def clean(self):
        if self.text == "":
            raise ValidationError("You can't have an empty text in item")

    def __str__(self):
        return self.text

    class Meta:
        ordering = ('id',)
        unique_together = ('list', 'text')

lists/forms.py
from django import forms

from lists.models import Item

EMPTY_ITEM_ERROR = "You can't have an empty list item"


class ItemForm(forms.ModelForm):
    """Форма для элемента списка."""

    def save(self, for_list):
        self.instance.list = for_list
        return super().save()

    class Meta:
        model = Item
        fields = ("text",)
        widgets = {
            "text": forms.TextInput(attrs={
                "placeholder": "Enter a to-do item",
                "class": "form-control input-lg",
            }),
        }
        error_messages = {
            "text": {"required": EMPTY_ITEM_ERROR}
        }

accounts/views.py
import sys
import uuid
from django.contrib import messages, auth
from django.contrib.auth.models import User
from django.contrib.sessions.models import Session
from django.core import mail
from django.http import HttpRequest
from django.shortcuts import render, redirect
from accounts.models import Token


def send_login_email(request: HttpRequest):
    """Выслать ссылку на логин по почте."""
    # print("run send_login_email")
    email = request.POST["email"]
    uid = str(uuid.uuid4())
    Token.objects.create(email=email, uid=uid)
    # print('saving uid', uid, 'for email', email, file=sys.stderr)
    url = request.build_absolute_uri(f"/accounts/login?uid={uid}")
    mail.send_mail(
        subject="Superlists login link",
        message=f"Use this link to log in site Superlists: \n\n{url}",
        from_email="superlists@admin.com",
        recipient_list=[email],
        fail_silently=False,
    )
    # # WARNING delete url from context before use in PRODUCTION (use not console EMAIL_BACKEND in settings.py)
    # return render(request, "login_email_sent.html")
    messages.success(
        request=request,
        message="Check your email, you'll find a message with a link that will log you into the site."
    )
    return redirect("/")


def login(request):
    """Регистрация в системе."""
    # print("run login view", file=sys.stderr)
    uid = request.GET.get('uid')
    user = auth.authenticate(uid=uid)
    if user is not None:
        auth.login(request, user)
    return redirect('/')


def logout(request):
    """Выход из системы."""
    auth.logout(request)
    return redirect('/')

lists/views.py
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.shortcuts import render, redirect
from django.http.request import HttpRequest
from django.views.decorators.http import require_POST

from functional_tests.base import DUPLICATE_ITEM_ERROR
from lists.forms import ItemForm
from lists.models import List

User = get_user_model()


def home_page(request: HttpRequest):
    """Домашняя страница."""
    return render(request, "home.html", context={"form": ItemForm()})


def view_list(request: HttpRequest, list_id):
    """Представление списка."""
    list_ = List.objects.get(id=list_id)
    form = ItemForm()
    if request.method == "POST":
        form = ItemForm(request.POST)
        if form.is_valid():
            try:
                form.save(for_list=list_)
                return redirect(list_)
            except IntegrityError:
                form.errors["text"] = DUPLICATE_ITEM_ERROR
    return render(request, "list.html", {"list": list_, "form": form})


def new_list(request):
    """Новый список."""
    form = ItemForm(data=request.POST)
    if form.is_valid():
        list_ = List.objects.create()
        if request.user.is_authenticated:
            list_.owner = request.user
        list_.save()
        form.save(for_list=list_)
        return redirect(list_)
    else:
        return render(request, "home.html", {"form": form})


def my_lists(request, email):
    owner = User.objects.get(email=email)
    return render(request, "my_lists.html", context={"owner": owner})


@require_POST
def share_list(request: HttpRequest, list_id):
    email = request.POST["email"]
    user = User.objects.get_or_create(email=email)[0]
    list_ = List.objects.get(pk=list_id)
    list_.shared_with.add(user)
    return redirect(list_)

accounts/templates/login_email_sent.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Email sent</title>
</head>

<body>

    <h1>Email sent</h1>
    <p>Check your email, you'll find a message with a link that will log you into the site.</p>
    {% if url %}
        <p>
            <a href="{{ url }}">{{ url }}</a>
        </p>
    {% endif %}


</body>

</html>

lists/templates/base.html
{% load static %}
{% load django_bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% bootstrap_messages %}

<!DOCTYPE html>
<html lang="en">
<head>
    <link href="{% static 'base.css' %}" rel="stylesheet">
    <meta charset="UTF-8">
    <title>To-Do lists</title>

</head>

<body>
    <nav class="navbar navbar-default" role="navigation">
        <div class="container-fluid">


            {% if user.email %}
            <ul class="nav navbar-nav navbar-left">
                <li><a href="{% url 'my_lists' user.email %}">My lists</a> </li>
            </ul>
            {% endif %}

            <a class="navbar-brand" href="/">Superlists</a>
            {% if user.email %}
                <ul class="nav navbar-nav navbar-right">
                    <li class="navbar-text">Logged in as {{ user.email }}</li>

                    <form method="post" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button type="submit">Log out</button>
                    </form>
<!--                    <li><a href="{% url 'logout' %}">Log out</a></li>-->

                </ul>
            {% else %}
                <form class="navbar-form navbar-right" method="POST" action="{% url 'send_login_email' %}">
                    <span>Enter email to log in:</span>
                    <input class="form-control" name="email" type="text" />
                    {% csrf_token %}
                </form>
            {% endif %}

        </div>
    </nav>

        <div class="row">
            <div class="col-md-12 col-md-offset-3 mt-4 p-5 bg-primary text-white rounded">
                <div class="text-center">
                    <h1>{% block header_text %}{% endblock %}</h1>

                    {% block list_form %}
                    <form method="POST" action="{% block form_action %}{% endblock %}">
                        {{ form.text }}
                        {% csrf_token %}
                        {% if form.errors %}
                            <div class="form-group has-error">
                                <div class="help-block">{{ form.text.errors }}</div>
                            </div>
                        {% endif %}
                    </form>
                    {% endblock %}

                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-md-offset-3">
                {% block table %}
                {% endblock %}
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-md-offset-3">
                {% block extra_content %}
                {% endblock %}
            </div>
        </div>

    </div>

<script src="/static/jquery-3.7.1.min.js"></script>
    <script src="/static/list.js"></script>
    <script>
        initialize();
    </script>



</body>

</html>

lists/templates/home.html
{% extends 'base.html' %}

{% block header_text %}Start a new To-Do list{% endblock %}

{% block form_action %}{% url 'new_list' %}{% endblock %}

lists/templates/list.html
{% extends 'base.html' %}

{% block header_text %}Your To-Do list{% endblock %}

{% block form_action %}{% url 'view_list' list.id %}{% endblock %}

{% block table %}
    <table id="id_list_table" class="table">
        {% for item in list.item_set.all %}
        <tr><td>{{ forloop.counter }}: {{ item.text }}</td></tr>
        {% endfor %}
    </table>
{% endblock %}


{% block extra_content %}
    <form method="POST" action="{% url 'share_list' list.pk  %}">
        <label for="email">Share by email:</label>
        <input type="text" id="email" name="email" placeholder="your-friend@example.com">
        <input type="submit" value="Share">
        {% csrf_token %}
    </form>

    {% if list.shared_with.all %}
    <p>Список совместно используется: </p>

    <ul>
        {% for user in list.shared_with.all %}
            <li>
                {{ user.email }}
            </li>
        {% endfor %}
    </ul>
    {% endif %}

{% endblock %}


</body>

</html>

lists/templates/my_lists.html
{% extends 'base.html' %}

{% block header_text %}My Lists{% endblock %}

{% block list_form %}{% endblock %}

{% block extra_content %}
    <h2>{{ owner.email }}'s lists</h2>
    <ul>
        {% for list in owner.list_set.all %}
            <li>
                <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
            </li>
        {% endfor %}
    </ul>

    {% if owner.my_list.all %}
        <p>Списки, для совместного редактирования: </p>
            {% for list in owner.my_list.all %}
                <li>
                    <a href="{{ list.get_absolute_url }}">{{ list.name }}</a>
                </li>
            {% endfor %}
    {% endif %}
{% endblock %}